<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="slorw.css">
</head>
<body>
    <nav class="navbar">
        <div class="comtainer">
            <div class="wrap">
                <div class="hamb">
                    <div class="hamb-field" id="hamb">
                        <span class="bar"></span>
                        <span class="bar"></span>
                        <span class="bar"></span>
                    </div>
                </div>
                <a href="#" class="logo" id="logo">MyWebsite</a>
                <ul class="menu" id="menu">
                    <li><a href="#"></a>Home</li>
                    <li><a href="#"></a>About</li>
                    <li><a href="#"></a>Services</li>
                    <li><a href="#"></a>Contact</li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="popup" id="popup"></div>


    <script src="oienfn.js"></script>
</body>
</html>
